directory: ~/Music/music
library: ~/Music/musiclibrary.db
paths:
    default: $albumartist - $album%aunique{}/$track $title
    singleton: $artist/$title
    comp: Compilations/$album%aunique{}/$track $title
    art_filename: cover
asciify_paths: true
write: yes
resume: ask
timid: yes

plugins: replaygain badfiles

replaygain:
  backend: bs1770gain

